In [17]:
import numpy as np

입력 데이터 생성

In [18]:
input = np.random.random(25).reshape(5,5)
input

array([[0.45957714, 0.26181405, 0.22633556, 0.29436161, 0.67993989],
       [0.54672573, 0.03661348, 0.47898127, 0.71440504, 0.67809006],
       [0.98097749, 0.36643927, 0.12704123, 0.47874706, 0.23620229],
       [0.34961404, 0.17677752, 0.07871377, 0.96997658, 0.72019312],
       [0.94218155, 0.39934473, 0.52830907, 0.02773984, 0.73193416]])

가중치 커널 생성

In [19]:
w = np.random.random(9).reshape(3,3)
w

array([[0.87415688, 0.46307588, 0.45638776],
       [0.05627318, 0.75015595, 0.61465668],
       [0.28512713, 0.59426342, 0.57374799]])

In [20]:
result_arr = []

for matrix_row in range(input.shape[0]-w.shape[0]+1):
  for matrix_col in range(input.shape[1]-w.shape[1]+1):
    result = []
    for w_row in range(w.shape[0]):
      for w_col in range(w.shape[1]):
        result.append(input[matrix_row+w_row,matrix_col+w_col] * w[w_row, w_col])
    result_arr.append(np.sum(result))

In [21]:
result = np.array(result_arr).reshape(input.shape[0]-w.shape[0]+1,-1)
result

array([[1.54927433, 1.72316286, 2.08038773],
       [1.37155486, 1.64374572, 2.58254219],
       [2.09493777, 1.7065819 , 2.20235048]])

패딩

In [22]:
padding_matrix = np.zeros((input.shape[0]+w.shape[0]-1, input.shape[1]+w.shape[1]-1))
padding_matrix

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [23]:
input

array([[0.45957714, 0.26181405, 0.22633556, 0.29436161, 0.67993989],
       [0.54672573, 0.03661348, 0.47898127, 0.71440504, 0.67809006],
       [0.98097749, 0.36643927, 0.12704123, 0.47874706, 0.23620229],
       [0.34961404, 0.17677752, 0.07871377, 0.96997658, 0.72019312],
       [0.94218155, 0.39934473, 0.52830907, 0.02773984, 0.73193416]])

In [24]:
for i in range(input.shape[0]):
  for j in range(input.shape[1]):
    padding_matrix[i+1][j+1] = input[i][j]

In [25]:
padding_matrix

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.45957714, 0.26181405, 0.22633556, 0.29436161,
        0.67993989, 0.        ],
       [0.        , 0.54672573, 0.03661348, 0.47898127, 0.71440504,
        0.67809006, 0.        ],
       [0.        , 0.98097749, 0.36643927, 0.12704123, 0.47874706,
        0.23620229, 0.        ],
       [0.        , 0.34961404, 0.17677752, 0.07871377, 0.96997658,
        0.72019312, 0.        ],
       [0.        , 0.94218155, 0.39934473, 0.52830907, 0.02773984,
        0.73193416, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])