In [ ]:
import numpy as np

입력 데이터 생성

In [ ]:
input = np.random.random(16).reshape(4,4)
input

array([[0.69630105, 0.98062141, 0.31126132, 0.60385103],
       [0.41160081, 0.65936305, 0.67091633, 0.79464866],
       [0.25562064, 0.3772345 , 0.0579391 , 0.97562818],
       [0.74501807, 0.378548  , 0.8962382 , 0.21717298]])

가중치 커널 생성

In [ ]:
w = np.random.random(4).reshape(2,2)
w

array([[0.47915972, 0.0276349 ],
       [0.21120514, 0.91373281]])

In [ ]:
result_arr = []

for matrix_row in range(input.shape[0]-w.shape[0]+1):
  for matrix_col in range(input.shape[1]-w.shape[1]+1):
    result = []
    for w_row in range(w.shape[0]):
      for w_col in range(w.shape[1]):
        result.append(input[matrix_row+w_row,matrix_col+w_col] * w[w_row, w_col])
    result_arr.append(np.sum(result))

In [ ]:
result = np.array(result_arr).reshape(input.shape[0]-w.shape[0]+1,-1)
result

array([[1.05015265, 1.23077507, 1.03362878],
       [0.61412389, 0.46709564, 1.24713663],
       [0.63615132, 1.08123025, 0.44245166]])