In [1]:
import numpy as np

입력 데이터 생성

In [2]:
input = np.random.random(16).reshape(4,4)
input

array([[0.44347376, 0.29017623, 0.62991373, 0.50209371],
       [0.63625638, 0.58489094, 0.8153437 , 0.67830812],
       [0.99001811, 0.15216859, 0.23262359, 0.32014961],
       [0.21619336, 0.33241801, 0.92530904, 0.02216692]])

가중치 커널 생성

In [3]:
w = np.random.random(4).reshape(2,2)
w

array([[0.90716266, 0.06596578],
       [0.82393991, 0.79375542]])

In [4]:
result_arr = []
stride_row = 2
stride_col = 2

for matrix_row in range(0, input.shape[0]-w.shape[0]+1, stride_row):
  for matrix_col in range(0, input.shape[1]-w.shape[1]+1, stride_col):
    result = []
    for w_row in range(w.shape[0]):
      for w_col in range(w.shape[1]):
        result.append(input[matrix_row+w_row,matrix_col+w_col] * w[w_row, w_col])
    result_arr.append(np.sum(result))

In [5]:
result = np.array(result_arr).reshape(int(input.shape[0]-w.shape[0]+1/2),-1)
result

array([[1.40994192, 1.81476018],
       [1.35013431, 1.01214052]])